# Spike earlyoom configuration
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Advanced → Memory to change
# Changelog reference: {{changelog_id}}
EARLYOOM_ARGS="-r 3600 -m {{earlyoom_threshold}} -s {{earlyoom_threshold}} --prefer '({{earlyoom_prefer}})' --avoid '({{earlyoom_protected}}|earlyoom)'"
