# Spike GRUB2 Configuration
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Advanced → Boot to change
# Changelog reference: {{changelog_id}}
GRUB_TIMEOUT={{grub_timeout}}
GRUB_TIMEOUT_STYLE={{grub_timeout_style}}
GRUB_DEFAULT=0
GRUB_DISABLE_RECOVERY=false
{{grub_theme_block}}GRUB_CMDLINE_LINUX_DEFAULT="{{boot_parameters_joined}}"
GRUB_CMDLINE_LINUX=""
GRUB_DISABLE_OS_PROBER=true
GRUB_DISABLE_SUBMENU=y
