# Spike Power Configuration
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Power to change
# Changelog reference: {{changelog_id}}
[Login]
HandleLidSwitch={{lid_close_action}}
HandleLidSwitchExternalPower={{lid_close_action_ac}}
HandlePowerKey={{power_button_action}}
IdleAction={{idle_action}}
IdleActionSec={{idle_action_sec}}
