# Spike NetworkManager Configuration
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Network to change
# Changelog reference: {{changelog_id}}
[main]
dhcp = {{dhcp_client}}
dns = {{dns_resolver}}
plugins = keyfile
[connection]
ipv6.method = auto
ipv6.ip6-privacy = 2
autoconnect = true
wifi.cloned-mac-address = preserve
[wifi]
scan-rand-mac-address = no
