# Spike PipeWire Configuration
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Sound to change
# Changelog reference: {{changelog_id}}
[context]
log.level = 1
log.timestamp = false
log.color = false
[properties]
default.clock.rate = {{sample_rate}}
default.clock.quantum = 1024
default.clock.min-quantum = 32
default.clock.max-quantum = 2048
default.clock.allowed-rates = [ {{sample_rate}} ]
