# Spike kernel module blacklist
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — regenerated from hardware detection + policy
# Changelog reference: {{changelog_id}}
{{module_blacklist_lines}}
