# Spike Memory Configuration
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Advanced → Memory to change
# Changelog reference: {{changelog_id}}
# Swappiness (lower = prefer RAM, higher = prefer swap)
vm.swappiness = {{swappiness}}
# VFS cache pressure
vm.vfs_cache_pressure = {{vfs_cache_pressure}}
# Transparent hugepages (controlled by kernel param, but set here too)
# (transparent_hugepage=madvise on kernel command line)
