# Spike ZRAM udev rule (legacy / fallback path; prefer zram-generator)
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Advanced → Memory to change
# Changelog reference: {{changelog_id}}
KERNEL=="zram0", ACTION=="add", ATTR{comp_algorithm}="{{zram_compression}}", ATTR{disksize}="{{zram_size_mb}}M", RUN+="/sbin/swapon --priority {{zram_priority}} /dev/zram0"
