# Spike ZRAM (systemd-zram-generator)
# Generated by spike-config at {{timestamp}}
# DO NOT EDIT — Use Settings → Advanced → Memory to change
# Changelog reference: {{changelog_id}}
[zram0]
zram-size = {{zram_size_mb}}M
compression-algorithm = {{zram_compression}}
swap-priority = {{zram_priority}}
