"""Basic spike-config skeleton tests (no root required)."""

from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


class SpikeConfigTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmpdir = tempfile.TemporaryDirectory()
        self.root = Path(self._tmpdir.name)
        os.environ["SPIKE_ROOT"] = str(self.root)
        os.environ["SPIKE_STATE_DIR"] = str(self.root / "var/lib/spike/config")
        os.environ["SPIKE_TEMPLATE_DIR"] = str(ROOT / "templates")
        os.environ["SPIKE_DEFAULT_STATE"] = str(ROOT / "data/default-state.json")
        # Fresh imports pick up env via paths helpers (read at call time).
        from spike_config import changelog, generate, state
        from spike_config.cli import main

        self.state = state
        self.generate = generate
        self.changelog = changelog
        self.main = main

    def tearDown(self) -> None:
        self._tmpdir.cleanup()
        for key in (
            "SPIKE_ROOT",
            "SPIKE_STATE_DIR",
            "SPIKE_TEMPLATE_DIR",
            "SPIKE_DEFAULT_STATE",
        ):
            os.environ.pop(key, None)

    def test_init_generate_validate(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--generate-all"]), 0)
        sysctl = self.root / "etc/sysctl.d/99-spike-memory.conf"
        self.assertTrue(sysctl.is_file())
        text = sysctl.read_text(encoding="utf-8")
        self.assertIn("vm.swappiness = 15", text)
        self.assertIn("Generated by spike-config", text)
        self.assertNotIn("{{", text)
        grub = self.root / "etc/default/grub"
        self.assertTrue(grub.is_file())
        grub_text = grub.read_text(encoding="utf-8")
        self.assertIn("zswap.enabled=0", grub_text)
        self.assertNotIn("GRUB_FONT=", grub_text)
        self.assertNotIn("GRUB_THEME=", grub_text)
        self.assertEqual(self.main(["--validate"]), 0)

    def test_state_set_and_regenerate(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--state-set", "memory", "swappiness", "30"]), 0)
        self.assertEqual(self.main(["--generate", "memory"]), 0)
        text = (self.root / "etc/sysctl.d/99-spike-memory.conf").read_text(encoding="utf-8")
        self.assertIn("vm.swappiness = 30", text)
        entries = self.changelog.load()
        self.assertTrue(any(e.get("setting") == "swappiness" for e in entries))

    def test_boot_count(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--boot-count", "reset"]), 0)
        self.assertEqual(self.main(["--boot-count", "increment"]), 0)
        self.assertEqual(self.main(["--boot-count", "increment"]), 0)
        path = self.root / "boot/.spike/boot-count"
        self.assertEqual(path.read_text(encoding="utf-8").strip(), "2")

    def test_templates_idempotent(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--generate", "memory"]), 0)
        first = (self.root / "etc/sysctl.d/99-spike-memory.conf").read_text(encoding="utf-8")
        # Strip timestamp/changelog lines for stability comparison of values
        self.assertEqual(self.main(["--generate", "memory"]), 0)
        second = (self.root / "etc/sysctl.d/99-spike-memory.conf").read_text(encoding="utf-8")
        def values(s: str) -> list[str]:
            return [ln for ln in s.splitlines() if ln.startswith("vm.")]

        self.assertEqual(values(first), values(second))

    def test_detect_gpu_storage_network_sysfs(self) -> None:
        from spike_config import detect as detect_mod

        fake = self.root / "fake-sys"
        pci = fake / "bus/pci/devices/0000:00:01.0"
        pci.mkdir(parents=True)
        (pci / "class").write_text("0x030000\n", encoding="utf-8")
        (pci / "vendor").write_text("0x1002\n", encoding="utf-8")
        (pci / "device").write_text("0x9850\n", encoding="utf-8")
        drv = fake / "bus/pci/drivers/radeon"
        drv.mkdir(parents=True)
        (pci / "driver").symlink_to(drv)

        block = fake / "block"
        sda = block / "sda"
        (sda / "queue").mkdir(parents=True)
        (sda / "size").write_text("500000000\n", encoding="utf-8")  # ~238 GiB
        (sda / "removable").write_text("0\n", encoding="utf-8")
        (sda / "queue" / "rotational").write_text("1\n", encoding="utf-8")
        # Removable USB should be ignored even if larger
        sdb = block / "sdb"
        (sdb / "queue").mkdir(parents=True)
        (sdb / "size").write_text("900000000\n", encoding="utf-8")
        (sdb / "removable").write_text("1\n", encoding="utf-8")
        (sdb / "queue" / "rotational").write_text("1\n", encoding="utf-8")

        net = fake / "class/net"
        wlan = net / "wlp1s0"
        wlan.mkdir(parents=True)
        (wlan / "wireless").mkdir()
        (wlan / "type").write_text("1\n", encoding="utf-8")
        wdrv = fake / "bus/pci/drivers/iwlwifi"
        wdrv.mkdir(parents=True)
        (wlan / "device").mkdir()
        (wlan / "device" / "driver").symlink_to(wdrv)
        eth = net / "enp2s0"
        eth.mkdir(parents=True)
        (eth / "type").write_text("1\n", encoding="utf-8")
        (eth / "device").mkdir()

        gpu: dict = {}
        storage: dict = {}
        network: dict = {}
        detect_mod._detect_gpu(gpu, sys_pci=fake / "bus/pci/devices")
        detect_mod._detect_storage(storage, sys_block=block)
        detect_mod._detect_network(network, sys_net=net)

        self.assertEqual(gpu["vendor"], "amd")
        self.assertEqual(gpu["driver"], "radeon")
        self.assertEqual(gpu["va_api_driver"], "radeonsi")
        self.assertEqual(storage["device"], "/dev/sda")
        self.assertEqual(storage["type"], "hdd")
        self.assertTrue(storage["rotational"])
        self.assertGreater(storage["size_gb"], 0)
        self.assertTrue(network["has_wifi"])
        self.assertEqual(network["wifi_driver"], "iwlwifi")
        self.assertTrue(network["has_ethernet"])

    def test_module_blacklist_policy(self) -> None:
        from spike_config import blacklist as bl

        empty = self.root / "empty-pci"
        empty.mkdir(parents=True)
        mods = bl.compute_module_blacklist(sys_pci=empty)
        self.assertIn("megaraid_sas", mods)
        self.assertIn("ib_core", mods)
        self.assertIn("parport", mods)
        for forbidden in ("nouveau", "iwlwifi", "usbcore", "i915", "amdgpu"):
            self.assertNotIn(forbidden, mods)

        # LSI MegaRAID vendor present → megaraid_sas / mptsas exempt
        pci = self.root / "raid-pci"
        dev = pci / "0000:01:00.0"
        dev.mkdir(parents=True)
        (dev / "vendor").write_text("0x1000\n", encoding="utf-8")
        (dev / "device").write_text("0x005b\n", encoding="utf-8")
        mods2 = bl.compute_module_blacklist(sys_pci=pci)
        self.assertNotIn("megaraid_sas", mods2)
        self.assertNotIn("mptsas", mods2)
        self.assertIn("ib_core", mods2)  # still no Mellanox

        # apply_blacklist_to_state writes security.module_blacklist
        st: dict = {"security": {"module_blacklist": []}}
        applied = bl.apply_blacklist_to_state(st, sys_pci=empty)
        self.assertEqual(st["security"]["module_blacklist"], applied)
        self.assertIn("hpsa", applied)

    def test_version_single_source(self) -> None:
        """CLI, pyproject, and packaging must share spike_config.__version__."""
        from spike_config import __version__

        self.assertRegex(__version__, r"^\d+\.\d+\.\d+")
        init_text = (ROOT / "spike_config" / "__init__.py").read_text(encoding="utf-8")
        self.assertIn(f'__version__ = "{__version__}"', init_text)

        pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
        self.assertIn('dynamic = ["version"]', pyproject)
        self.assertIn('version = { attr = "spike_config.__version__" }', pyproject)
        self.assertNotRegex(pyproject, r'(?m)^version\s*=\s*"')

        pkg = ROOT.parents[1] / "scripts" / "package-spike-config.sh"
        script = pkg.read_text(encoding="utf-8")
        self.assertIn("__version__", script)
        self.assertNotRegex(script, r'VERSION="\$\{SPIKE_CONFIG_VERSION:-[0-9]')


if __name__ == "__main__":
    unittest.main()
