"""Basic spike-config skeleton tests (no root required)."""

from __future__ import annotations

import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


class SpikeConfigTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmpdir = tempfile.TemporaryDirectory()
        self.root = Path(self._tmpdir.name)
        os.environ["SPIKE_ROOT"] = str(self.root)
        os.environ["SPIKE_STATE_DIR"] = str(self.root / "var/lib/spike/config")
        os.environ["SPIKE_TEMPLATE_DIR"] = str(ROOT / "templates")
        os.environ["SPIKE_DEFAULT_STATE"] = str(ROOT / "data/default-state.json")
        # Fresh imports pick up env via paths helpers (read at call time).
        from spike_config import changelog, generate, state
        from spike_config.cli import main

        self.state = state
        self.generate = generate
        self.changelog = changelog
        self.main = main

    def tearDown(self) -> None:
        self._tmpdir.cleanup()
        for key in (
            "SPIKE_ROOT",
            "SPIKE_STATE_DIR",
            "SPIKE_TEMPLATE_DIR",
            "SPIKE_DEFAULT_STATE",
        ):
            os.environ.pop(key, None)

    def test_init_generate_validate(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--generate-all"]), 0)
        sysctl = self.root / "etc/sysctl.d/99-spike-memory.conf"
        self.assertTrue(sysctl.is_file())
        text = sysctl.read_text(encoding="utf-8")
        self.assertIn("vm.swappiness = 15", text)
        self.assertIn("Generated by spike-config", text)
        self.assertNotIn("{{", text)
        grub = self.root / "etc/default/grub"
        self.assertTrue(grub.is_file())
        self.assertIn("zswap.enabled=0", grub.read_text(encoding="utf-8"))
        self.assertEqual(self.main(["--validate"]), 0)

    def test_state_set_and_regenerate(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--state-set", "memory", "swappiness", "30"]), 0)
        self.assertEqual(self.main(["--generate", "memory"]), 0)
        text = (self.root / "etc/sysctl.d/99-spike-memory.conf").read_text(encoding="utf-8")
        self.assertIn("vm.swappiness = 30", text)
        entries = self.changelog.load()
        self.assertTrue(any(e.get("setting") == "swappiness" for e in entries))

    def test_boot_count(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--boot-count", "reset"]), 0)
        self.assertEqual(self.main(["--boot-count", "increment"]), 0)
        self.assertEqual(self.main(["--boot-count", "increment"]), 0)
        path = self.root / "boot/.spike/boot-count"
        self.assertEqual(path.read_text(encoding="utf-8").strip(), "2")

    def test_templates_idempotent(self) -> None:
        self.assertEqual(self.main(["--init-state"]), 0)
        self.assertEqual(self.main(["--generate", "memory"]), 0)
        first = (self.root / "etc/sysctl.d/99-spike-memory.conf").read_text(encoding="utf-8")
        # Strip timestamp/changelog lines for stability comparison of values
        self.assertEqual(self.main(["--generate", "memory"]), 0)
        second = (self.root / "etc/sysctl.d/99-spike-memory.conf").read_text(encoding="utf-8")
        def values(s: str) -> list[str]:
            return [ln for ln in s.splitlines() if ln.startswith("vm.")]

        self.assertEqual(values(first), values(second))


if __name__ == "__main__":
    unittest.main()
